//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItem
    {
        public int ID { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public string ProductImgPath { get; set; }
        public Nullable<int> ProductOrder { get; set; }
        public Nullable<int> ProductPopular { get; set; }
        public string Status { get; set; }
    }
}
