//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorAnalytic
    {
        public int ID { get; set; }
        public string ANTRDATE { get; set; }
        public string ANTRTIME { get; set; }
        public string ANSESID { get; set; }
        public string ANIPDET { get; set; }
        public string ANBROW { get; set; }
        public string ANBROWVER { get; set; }
        public string ANOPRSYS { get; set; }
        public string ANTRYEAR { get; set; }
        public string ANTRMONTH { get; set; }
    }
}
