//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VtradellcdbEntities : DbContext
    {
        public VtradellcdbEntities()
            : base("name=VtradellcdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BrandItem> BrandItems { get; set; }
        public DbSet<CategoryItem> CategoryItems { get; set; }
        public DbSet<ContactDetail> ContactDetails { get; set; }
        public DbSet<ProductImageList> ProductImageLists { get; set; }
        public DbSet<ProductInfo> ProductInfoes { get; set; }
        public DbSet<ProductItem> ProductItems { get; set; }
        public DbSet<SubscribeDetail> SubscribeDetails { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<VisitorAnalytic> VisitorAnalytics { get; set; }
    }
}
